language: python
python:
  - "3.7.1"
# command to install dependencies
services:
  - postgresql
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE DATABASE stackover;" -U postgres
  - psql -c "CREATE USER ogwang WITH PASSWORD 'adonis123';" -U postgres
# command to run tests
script: 
  - py.test --cov=app -v
after_success:
  - coveralls
